version: '2.2'

services:
  srsepc:
    container_name: virtual-srsepc
    build: .
    command:
      - srsepc
      - epc.conf
      - --mme.mme_bind_addr=10.80.95.10
      - --spgw.gtpu_bind_addr=10.80.95.10
    networks:
      corenet:
        ipv4_address: 10.80.95.10
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    devices:
      - /dev/net/tun
  srsenb:
    container_name: virtual-srsenb
    build: .
    command:
      - srsenb
      - enb.conf
      - --enb.mme_addr=10.80.95.10
      - --enb.gtp_bind_addr=10.80.95.11
      - --enb.s1c_bind_addr=10.80.95.11
      - --enb_files.sib_config=sib.conf
      - --rf.device_name=zmq
      - --rf.device_args=fail_on_disconnect=true,tx_port=tcp://10.80.97.11:2000,rx_port=tcp://10.80.97.10:2001,id=enb,base_srate=23.04e6"
    networks:
      corenet:
        ipv4_address: 10.80.95.11
      rfnet:
        ipv4_address: 10.80.97.11
    cap_add:
      - SYS_NICE
    depends_on:
        - srsepc
  srsue:
    container_name: virtual-srsue
    build: .
    command:
      - srsue
      - ue.conf
      - --rf.device_name=zmq
      - --rf.device_args=tx_port=tcp://10.80.97.10:2001,rx_port=tcp://10.80.97.11:2000,id=ue,base_srate=23.04e6"
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    devices:
        - /dev/net/tun
    networks:
      rfnet:
        ipv4_address: 10.80.97.10
    depends_on:
      - srsenb

networks:
  corenet:
    ipam:
      driver: default
      config:
        - subnet: 10.80.95.0/24
  rfnet:
    ipam:
      driver: default
      config:
        - subnet: 10.80.97.0/24
